global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'spring_micrometer'
    metrics_path: '/cep/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.0.109:8082']